---
swagger: "2.0"
info:
  description: |
    The API for Arouse, the Decentralized Adult Marketplace
  version: 1.0.0
  title: Arouse API
host: virtserver.swaggerhub.com
basePath: /arouse-api/arouse-api/1.0.0
schemes:
- https
- http
paths:
  /asset:
    post:
      tags:
      - asset
      summary: Add a new asset for a content creator
      operationId: addAsset
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Asset binary object hash to IFPS file
        required: true
        schema:
          $ref: '#/definitions/Asset'
      responses:
        405:
          description: Invalid input
  /asset/{assetId}:
    get:
      tags:
      - asset
      summary: Find asset by ID
      description: Returns a single asst
      operationId: getAssetById
      produces:
      - application/json
      parameters:
      - name: assetId
        in: path
        description: ID of asset to return
        required: true
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Asset'
          responseSchema:
            $ref: '#/definitions/Asset'
        400:
          description: Invalid ID supplied
        404:
          description: Asset not found
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: Create a new buyer or seller account
      operationId: createUser
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: Created user object
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
  /user/{userId}:
    get:
      tags:
      - user
      summary: Get buyer/seller details
      description: Get details of a buyer or seller
      operationId: getUser
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        description: ID of user to return
        required: true
      responses:
        default:
          description: successful operation
definitions:
  Asset:
    type: object
    properties:
      name:
        type: string
      price:
        type: integer
        format: int64
      description:
        type: string
      avater:
        type: string
        format: url
    example:
      price: 0
      avater: http://example.com/aeiou
      name: name
      description: description
  User:
    type: object
    properties:
      uuid:
        type: integer
        format: int64
      username:
        type: string
      description:
        type: string
    example:
      description: description
      uuid: 0
      username: username
